### ISSUE TITLE
Can't understand how to setup multi-tenancy

### ISSUE THREAD

**Issue by ghost** [swoldanski/odoo-nginx-docker-multitenant#3]
Hi, 

I have cloned this git repo into a Ubuntu 14.04 instance with docker installed. I did the following steps:
- made no changes to the nginx.conf that was provided
- bash odoo-prepare.sh
- bash odoo-start.sh

When I run "docker ps", I see 3 containers running. When I visit http://my_ip_address, I get redirected to:

http://my_ip_address/web/database/selector

I fill out the form (Screenshot attached) but after hitting "Create database", I get redirected back to the same url (/web/database/selector).

I checked the odoo logs at /var/log/odoo/ on the odoo container but there are no logs. 

Do you know why this is happening? How can I fix it?

![screen shot 2016-06-28 at 12 01 48](https://cloud.githubusercontent.com/assets/20149603/16403473/1fe919c2-3d28-11e6-9233-2c87cb4c56a0.png)

**Comment by swoldanski** [comment]
multi tenacy is domain based. you can't use ip address to reach your new tenant. just add to your local hosts file ip of your machine and domain for your new database, eg.

172.16.x.x mytenant.com

and create new database of name mytenant-com
